name = "LibSpatialIndex"
uuid = "f19c2e90-9d16-5f2d-a2a7-af3fb29e4907"
license = "MIT"
version = "0.2.2"

[deps]
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
LibSpatialIndex_jll = "00e98e2a-4326-5239-88cb-15dcbe1c18d0"

[compat]
Aqua = "0.7"
GeoInterface = "1"
LibSpatialIndex_jll = "1.9"
julia = "1.6"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
